### ISSUE TITLE
Debugging - Crashes/Poor compositor performance

### ISSUE THREAD

**Issue by TomBZombie** [faho/kwin-tiling#86] opened 2017-06-10 10:33 UTC
Is there any way to debug this? The compositor will crash and restart, with this running, desktop performance is also considerably worse on my desktop. 
Laptop:
Macbook Pro 11,5 AMD GPU, radeon driver 2880x1800

Desktop:
Intel Xeon  X5670, nvidia 980ti, binary driver, 3840x2160

On the laptop, which has significantly worse 3d performance, desktop performance is perfect. On the desktop, certain applications cause the compositor to crash and kwin to restart or performance to significantly diminish. I'm using the 3d cube desktop switch effect and the transition becomes jerky as soon as X2GoClient is opened, menus will become slow to open, etc. Once it's closed, performance is restored. If there are many windows open, x2goclient will actually cause kwin to crash, so it's obviously running out of memory .

Some windows will also freeze but `maximize` or making them change size by opening/closing different windows will make them respond.

This doesn't happen with kwin-tiling disabled and my laptop is completely unaffected and works flawlessly, so it could be a nvidia driver issue, but I'd like to debug this.

**Comment by faho** [comment] 2017-06-10 11:58
So, first of all: A crash is pretty much by definition not the script's fault. No matter what it does, KWin should not crash. It's possible this is an issue in the driver (one which KWin could probably work around, but knowing KWin upstream probably won't), or it's one in KWin.

>Some windows will also freeze but maximize or making them change size by opening/closing different windows will make them respond.

That's #6, which I've reported upstream ages ago.

-----

>On the desktop, certain applications cause the compositor to crash and kwin to restart or performance to significantly diminish

Okay, the first thing to do here is to figure out the "certain applications". X2GoClient is one, but if I understand correctly that requires a bunch of setup which makes it hard to test. Do you have any others? It's of course possible that X2GoClient triggers a weird path (it's a remote connection thing?) so it won't show up with anything else.

The next thing is to get debug output (launch `kwin_x11 --replace` in a terminal) and a crash dump (if you're using systemd, check `coredumpctl info kwin_x11` - it should already have collected those). It might also be possible to run kwin_x11 under gdb (see https://community.kde.org/KWin/Debugging).

**Comment by TomBZombie** [comment] 2017-06-10 12:16
Thanks for the quick response!

Just launching x2goclient without any server configured causes the problem. However, I think this could be a configuration issue. On a brand new user, I don't have the compositor crash/slowdown when launching x2goclient. I have had kde5 installed since plasma 5.1.0 and I'm currently on  5.10.1 so it could well be some configuration change between versions during the various upgrades. I'll delete my  plasma config and reconfigure it to see what, if anything, triggers the performance issue.

As for #6 ,I have experienced the issue with a variety of applications: Chromium, Dolphin, Thunderbird, Submlime Text 3. It's always possible to work around it by forcing the window to resize, I wonder if there's a way to script toggling maximize quickly  as a workaround? Of course I've no idea how to detect when it's happened.

**Comment by faho** [comment] 2018-01-23 20:45
Closing this as a duplicate of #6.

**Closed by faho** 2018-01-23 20:45 UTC
