### ISSUE TITLE
Shortcuts not working (commented)

### ISSUE THREAD

**Issue by aleskandro** [faho/kwin-tiling#68] opened 2016-10-26 11:38 UTC
Hi, I read that in the commit 5ed3610b5524b61ea6537f3946559b5fb85f2914 you disabled the registerShortcut functions. Why? Is it now safe to get them in the same or another way?

**Comment by faho** [comment] 2016-10-26 12:42
Currently, these functions aren't working because of a kwin bug (that is in the process of being fixed now). Trying them causes errors, so I disabled them.

**Comment by aleskandro** [comment] 2016-10-27 13:44
Is there another way to get the functions linked by the shortcuts disabled working?

**Comment by faho** [comment] 2016-10-27 13:51
The functions themselves work. But there's no way to trigger them from the outside, and adding them somewhere randomly doesn't make sense. So: No.

**Comment by ohjames** [comment] 2016-10-29 15:14
You could do:

```
if (KWin.registerShortcut) {
}
```

That way the code will start working once my patch has landed (it's been approved, just waiting to get a kde developer account so I can push the commit) or for those who've patched their own KDE.

**Comment by faho** [comment] 2016-10-29 15:31
Or I could wait for your patch to land and then just uncomment it. IIRC it just prints errors without it (i.e. it doesn't crash or anything), so that's the simplest way of doing it.

**Comment by ohjames** [comment] 2016-10-29 15:59
Hm, I still think it's better to search for it, then people running different versions of KDE can run your script. I run Arch but Kubuntu sometimes takes a good while to get the latest version and many people run LTE etc.

**Comment by ohjames** [comment] 2016-10-29 16:01
For me it crashed when I try to use registerShortcut in unlatched KDE (via KWin... the global version won't be supported in Qml).

**Comment by ohjames** [comment] 2016-11-05 13:05
KWin.registerShortcut is in the latest plasma which was released a few days ago.

You'll have to change the code from `registerShortcut` to `KWin.registerShortcut` and you will have to check for it before calling it... otherwise it'll crash for those without it. I'm pretty sure `registerShortcut` isn't defined in declarativescript anymore, or if it ever has been.

**Comment by faho** [comment] 2016-11-05 13:35
Woohoo!

@ohjames: Thanks!

**Closed** 2016-11-05 13:34 UTC

**Comment by piotr-dobrogost** [comment] 2016-11-08 21:35
> KWin.registerShortcut is in the latest plasma which was released a few days ago.

Which is version...?

**Comment by faho** [comment] 2016-11-08 21:59
@piotr-dobrogost: 5.8.3 has it.

**Comment by jayx101** [comment] 2016-11-10 04:22
Hi @faho ,

Have tried to install the latest fixes but no changes esp. re the shortcuts.
What is the best way to re-install? I have deleted the folder, pulled the lastest version from git and run plasmapkg2..

![image](https://cloud.githubusercontent.com/assets/12130063/20164475/18a6cc22-a740-11e6-8e41-edcc2a40beba.png)

I have also removed and re-installed both these scripts and then did a kwin --replace

The meta pgup and meta pgdown not doing anything.

**Comment by faho** [comment] 2016-11-10 09:46
@jayx101: Do you have kwin 5.8.**3**? Anything less than that doesn't have the support.

Also, you'll probably want to uninstall those scripts and _then_ do plasmapkg2. Also check your ~/.local/share/kwin/scripts to confirm that there's only one "kwin-script-tiling" and no other tiling script.

Then run `kwin_x11 --replace` in a terminal and confirm it's printing stuff related to tiling.

**Comment by piotr-dobrogost** [comment] 2016-11-10 10:05
@faho 
Is `kwin_x11 --replace` better than `kwin --replace`?

**Comment by faho** [comment] 2016-11-10 15:46
@piotr-dobrogost: I don't have a `kwin` binary, I only have `kwin_x11` and `kwin_wayland`, so `kwin --replace` just won't work for me.

**Comment by jayx101** [comment] 2016-11-11 03:59
Upgraded to Neon with  Kubuntu and its working! OMG sooo good!

Thank you for updates!
#madeKDEgreatagain

Probably off topic, but what distro have you personally found that Plasma
runs best/stable?

**Comment by faho** [comment] 2016-11-11 11:06
> Probably off topic, but what distro have you personally found that Plasma runs best/stable?

Personally, I run arch. Which means I get the newest Plasma, which I feel tends to work well with it since the newer releases are pretty much pure improvement without many regressions.

I don't have a "user-friendly" KDE distro to recommend. I've heard good things about Neon and Suse, and bad things about Kubuntu, but I've not used either of them.
